// Generated by CoffeeScript 1.8.0
(function() {
  var app;
  app = angular.module('raty', []);
  return app.directive('raty', function() {
    return {
      restrict: 'A',
      scope: {
        ngModel: '='
      },
      link: function(scope, element, attrs) {
        var defaults;
        defaults = {
          click: function(score, evt) {
            return scope.$apply(function() {
              return scope.ngModel = score;
            });
          },
          readonly: attrs.readonly === 'true'
        };
        $(element).raty({
          click: defaults.click,
          readOnly: defaults.readonly
        });
        return scope.$watch('ngModel', function(newVal) {
          if (defaults.readonly) {
            scope.ngModel = newVal || 1;
            $(element).raty({
              readOnly: true,
              score: scope.ngModel
            });
            return false;
          }
          if (newVal) {
            return $(element).raty('score', newVal);
          } else {
            return scope.ngModel = 1;
          }
        });
      }
    };
  });
})();
